import React from 'react'
import { useEffect } from 'react';

export default function TransparentCovers() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <div style={{ textAlign: 'left', backgroundColor: '#F0EBD8', color: '#0D1321', padding: '50px' }}>
      <p style={{ fontSize: '32px' }}>Transparent Roofs, LITRA Transparent Verandas</p>
      <p style={{ fontSize: '24px' }}>Protect the garden with Transparent Verandas. Quality transparent covers guaranteed by LITRA</p>
      <p>LITRA transparent covers are covers designed and made by our engineers tailored to the needs of the customer who requests them.</p>
      <img style={{ width: 'auto', height: '500px' }} src="img/9.jpg" alt="Something went wrong..." />
      <p>The unique feature that sets these covers apart from all other types of covers is that this cover is a transparent cover.</p>
      <p>The fact that it is transparent ensures that those inside can observe the sky while having the sensation of being in the open air. However, the fact that the covering material used (PVC, Plexiglass or Polycarbonate) is transparent does not damage the effectiveness of the protection that our transparent verandas guarantee to our customers. In fact, they are able to protect your home or business from rain, strong winds (up to 150 km/h), high snow loads, UV rays, and other atmospheric conditions.</p>
      <p>Our transparent outdoor covers are particularly recommended for those who want to increase their business profits by attracting a large number of customers (so restaurants, hotels, discos, bars, pubs but also all other types of businesses benefit most from them).</p>
      <p style={{ fontSize: '24px' }}>Retractable Transparent Covers</p>
      <p>The LITRA transparent cover is equipped with a spectacular and innovative retractable system (available in a manual version and a motorized version) which allows them to open for 2/3 of the length of the structure thus allowing fresh air to enter the room. The retractable system patented by LITRA is particularly useful in situations where there are a large number of people in a closed room; in fact, "overcrowding" of a room often results in inconveniences such as excessive temperatures and unwanted odors. By opening your transparent roof this problem will no longer exist, the recirculation of air generated by opening the roof will guarantee greater comfort to your customers and a much more positive experience that they will certainly want to repeat. Generally, those who install our transparent covers in commercial activities increase their revenue by 5% to 20% from the first month.</p>
      <p style={{ fontSize: '20px' }}>LITRA develops different types of transparent covers such as:</p>
      <ul>
        <li>Transparent coverings for terraces</li>
        <li>Transparent covers for pergolas</li>
        <li>Transparent roof coverings (also known as skylights)</li>
        <li>Transparent covers for transparent verandas</li>
        <li>Transparent porch covers</li>
        <li>And other types of transparent outdoor coverings</li>
      </ul>
      <p>The quality offered for our transparent covers is truly high and was achieved after several years of research, improvements and today LITRA also installs its products outside our peninsula. The innovative aluminum structure painted with a special antioxidant paint and the extreme resistance of the materials used as covering (PVC, Plexiglas or Polycarbonate), guarantee our products a unique quality and a truly convenient value for money!</p>
      <p>Our transparent covers are designed to prevent the phenomenon of condensation, and are designed for the installation of air conditioning and heating systems. The retractable system with which our transparent covers are equipped is a self-lubricating system and this means that your cover will become just a joy to enjoy for you, your home or your business.</p>
      <p>However, our experts always remain at your disposal and will be able to advise you on the best coverage for your space to be covered and, to this end, we invite you to contact us for any questions or doubts</p>
      <p>All LITRA products are guaranteed for 5 years</p>
    </div>
  )
}
